'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,BarChart3,RefreshCw,Loader2} from 'lucide-react';
import {toast} from 'sonner';
import type {Traffic} from '@/lib/catalog';
export function reportUrl(url:string){try{return 'https://www.similarweb.com/website/'+new URL(url).hostname.replace(/^www\./,'')+'/#overview'}catch{return 'https://www.similarweb.com/website/'}}
export function TrafficSummary({traffic,url}:{traffic:Traffic|null;url:string}){return <section className="traffic-panel"><div className="section-title"><h3><BarChart3 size={18}/>官网流量</h3><a href={reportUrl(url)} target="_blank" rel="noreferrer">查看第三方报告<ArrowUpRight size={14}/></a></div>{traffic?<><div className="traffic-number">{Intl.NumberFormat('zh-CN').format(traffic.visits)}<span>次访问 / 月</span></div><div className="traffic-caption">{traffic.month} · 全球 · 桌面端 + 移动端 · 第三方估算</div>{traffic.history&&traffic.history.length>1&&<div className="traffic-chart" aria-label="近几个月访问量趋势">{traffic.history.map(h=><div key={h.month} className="traffic-bar"><span>{Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1}).format(h.visits)}</span><div style={{height:Math.max(3,h.visits/Math.max(1,...traffic.history!.map(t=>t.visits))*80)}}/><small>{h.month.slice(5)}月</small></div>)}</div>}<div className="traffic-caption"><a href={traffic.sourceUrl} target="_blank" rel="noreferrer">来源：{traffic.source}<ArrowUpRight size={12}/></a> · {traffic.method==='manual'?'手动录入':'服务同步'} · 更新于 {new Date(traffic.updatedAt).toLocaleDateString('zh-CN')}</div><p className="traffic-disclaimer">这是官网访问次数估算，不代表独立访客、注册用户或付费用户。</p></>:<div className="traffic-empty"><strong>暂无官网流量数据</strong><p>可查看第三方报告，或在编辑时录入带来源的月访问量。数据缺失不代表流量为零。</p></div>}</section>}
export function TrafficEditor({traffic,url,onChange}:{traffic:Traffic|null;url:string;onChange:(t:Traffic|null)=>void}){const [configured,setConfigured]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[manual,setManual]=useState(false),[month,setMonth]=useState(traffic?.month||''),[visits,setVisits]=useState(traffic?.visits?.toString()||''),[source,setSource]=useState(traffic?.source||'Similarweb'),[sourceUrl,setSourceUrl]=useState(traffic?.sourceUrl||reportUrl(url));useEffect(()=>{fetch('/api/traffic').then(r=>r.json()).then(d=>setConfigured(d.configured)).catch(()=>setConfigured(null))},[]);async function refresh(){setBusy(true);try{const r=await fetch('/api/traffic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw Error(d.error);onChange(d.traffic);setMonth(d.traffic.month);setVisits(String(d.traffic.visits));setSource(d.traffic.source);setSourceUrl(d.traffic.sourceUrl);toast.success('流量已读取，保存产品后生效')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}function apply(){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)||visits.trim()===''||!Number.isFinite(Number(visits))||Number(visits)<0||!source.trim()){toast.error('请填写统计月份、有效访问量和数据来源');return}try{const u=new URL(sourceUrl);if(!['http:','https:'].includes(u.protocol))throw Error()}catch{toast.error('请填写有效的数据来源链接');return}onChange({month,visits:Number(visits),source:source.trim(),sourceUrl,updatedAt:new Date().toISOString(),method:'manual'});setManual(false);toast.success('流量快照已更新，保存产品后生效')}
return <div><TrafficSummary traffic={traffic} url={url}/><div className="traffic-actions"><button type="button" className="manual" disabled={busy||configured!==true} onClick={refresh}>{busy?<Loader2 size={15} className="spin"/>:<RefreshCw size={15}/>}同步流量</button><button type="button" className="manual" onClick={()=>setManual(!manual)}>{manual?'收起录入':'手动录入数据'}</button>{traffic&&<button type="button" className="text-button" onClick={()=>onChange(null)}>清除快照</button>}</div><p className="hint service-state">{configured===true?'已连接 Similarweb，同步会使用你的数据服务额度。':configured===false?'自动同步尚未接入；可通过上方报告入口查询并录入数据。':'暂时无法确认数据服务状态，请稍后重试。'}</p>{manual&&<div className="manual-traffic"><div className="input-pair"><label>统计月份<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label>月访问量（全球）<input type="number" min="0" step="1" value={visits} onChange={e=>setVisits(e.target.value)} placeholder="例如 125000"/></label></div><label>数据来源<input value={source} onChange={e=>setSource(e.target.value)} placeholder="例如 Similarweb" maxLength={100}/></label><label>来源报告链接<input type="url" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/></label><p className="hint">请录入全球、桌面端与移动端合计的月访问次数，并保留报告来源。</p><button type="button" className="manual" onClick={apply}>应用流量快照</button></div>}</div>}
